"""Compiled LLM-cliche candidate battery, five sources.

W  Wikipedia WikiProject AI Cleanup, "Signs of AI writing" (community-maintained)
K  Kobak et al., Science Advances 2025, excess-vocabulary study (quantitative)
S  slopdetector.org tiered AI words list (2026)
C  contentbeta.com 300+ AI words and phrases (2026)
E  enhancepost.com AI slop words and phrases (2026)

TERM entries generate a \b-anchored, \s+-joined, case-insensitive rule.
RAW entries carry a hand-written pattern where a term cannot express it.
"""

# (id, term, family, hint, sources)
TERMS = [
  # --- ceremony: announcing a tone instead of having it ---
  ("worth-stating",      "worth stating",        "ceremony", "announcing plainness instead of being plain", "WE"),
  ("worth-noting",       "worth noting",         "ceremony", "if it is worth saying, say it", "WKSCE"),
  ("worth-mentioning",   "worth mentioning",     "ceremony", "if it is worth saying, say it", "WE"),
  ("worth-pointing-out", "worth pointing out",   "ceremony", "if it is worth saying, say it", "W"),
  ("worth-highlighting", "worth highlighting",   "ceremony", "if it is worth saying, say it", "W"),
  ("important-to-note",  "important to note",    "ceremony", "say the thing without ranking it", "WSCE"),
  ("bears-mentioning",   "bears mentioning",     "ceremony", "say the thing", "E"),
  ("cannot-be-overstated","cannot be overstated","ceremony", "give the measure instead", "E"),
  ("goes-without-saying","goes without saying",  "ceremony", "then do not say it", "E"),
  ("needless-to-say",    "needless to say",      "ceremony", "then do not say it", "E"),
  ("to-be-direct",       "to be direct",         "ceremony", "open with the answer itself", "own"),
  ("to-be-honest",       "to be honest",         "ceremony", "open with the answer itself", "E"),
  ("lets-be-honest",     "let's be honest",      "ceremony", "open with the answer itself", "E"),
  ("the-truth-is",       "the truth is",         "ceremony", "open with the answer itself", "E"),
  ("heres-the-thing",    "here's the thing",     "ceremony", "cut the announcement", "SCE"),
  ("heres-the-deal",     "here's the deal",      "ceremony", "cut the announcement", "SC"),
  ("heres-the-kicker",   "here's the kicker",    "ceremony", "cut the announcement", "CE"),
  ("make-no-mistake",    "make no mistake",      "ceremony", "cut the announcement", "E"),
  ("let-me-be-clear",    "let me be clear",      "ceremony", "then be clear", "own"),
  ("short-version-is",   "the short version is", "ceremony", "open with the answer itself", "own"),
  ("straight-answer",    "a straight answer",    "ceremony", "open with the answer itself", "own"),
  ("real-question-is",   "the real question is", "ceremony", "ask it", "E"),
  ("at-its-core",        "at its core",          "ceremony", "state the thing", "E"),
  ("heart-of-the-matter","the heart of the matter","ceremony","state the thing", "E"),
  ("let-that-sink-in",   "let that sink in",     "ceremony", "cut it", "E"),
  ("read-that-again",    "read that again",      "ceremony", "cut it", "E"),
  ("fact-of-the-matter", "the fact of the matter","ceremony","cut it", "E"),

  # --- scene setting ---
  ("fast-paced-world",   "in today's fast-paced world","opener","cut the scene-setting", "SCE"),
  ("todays-digital-age", "in today's digital age","opener", "cut the scene-setting", "SCE"),
  ("todays-world",       "in today's world",     "opener", "cut the scene-setting", "C"),
  ("in-a-world-where",   "in a world where",     "opener", "cut the scene-setting", "SCE"),
  ("in-an-era-of",       "in an era of",         "opener", "cut the scene-setting", "E"),
  ("in-the-era-of",      "in the era of",        "opener", "cut the scene-setting", "C"),
  ("in-the-age-of",      "in the age of",        "opener", "cut the scene-setting", "own"),
  ("in-the-realm-of",    "in the realm of",      "opener", "name the field", "KSCE"),
  ("in-the-world-of",    "in the world of",      "opener", "name the field", "C"),
  ("imagine-a-world",    "imagine a world",      "opener", "cut the scene-setting", "E"),
  ("picture-this",       "picture this",         "opener", "cut the scene-setting", "SCE"),
  ("ever-wondered",      "ever wondered",        "opener", "cut the scene-setting", "SC"),
  ("when-it-comes-to",   "when it comes to",     "opener", "name the subject directly", "SE"),
  ("ever-evolving",      "ever-evolving",        "opener", "say what changed", "SE"),
  ("evolving-landscape", "evolving landscape",   "opener", "say what changed", "W"),
  ("digital-landscape",  "digital landscape",    "opener", "name the thing", "S"),
  ("landscape-of",       "the landscape of",     "opener", "name the thing", "WS"),

  # --- tier-one vocabulary ---
  ("delve",              "delve",                "tier1",  "say what you looked at", "WKSCE"),
  ("tapestry",           "tapestry",             "tier1",  "name the thing", "WSCE"),
  ("testament-to",       "testament to",         "tier1",  "state the evidence", "WSE"),
  ("underscore",         "underscore",           "tier1",  "say the effect", "WKSE"),
  ("elucidate",          "elucidate",            "tier1",  "explain it", "KS"),
  ("myriad",             "myriad",               "tier1",  "give the number", "S"),
  ("plethora",           "plethora",             "tier1",  "give the number", "S"),
  ("realm",              "realm",                "tier1",  "name the field", "KSCE"),
  ("paradigm-shift",     "paradigm shift",       "tier1",  "say what changed", "SE"),
  ("synergy",            "synergy",              "tier1",  "name the mechanism", "SE"),
  ("holistic",           "holistic",             "tier1",  "say what it covers", "SE"),
  ("catalyze",           "catalyze",             "tier1",  "say what caused what", "SE"),
  ("juxtapose",          "juxtapose",            "tier1",  "say what you compared", "KS"),
  ("galvanize",          "galvanize",            "tier1",  "say what happened", "S"),
  ("epitomize",          "epitomize",            "tier1",  "state the evidence", "S"),
  ("unravel",            "unravel",              "tier1",  "say what you found", "S"),
  ("supercharge",        "supercharge",          "tier1",  "give the delta", "SCE"),
  ("spearhead",          "spearhead",            "tier1",  "name the actor", "SE"),
  ("catapult",           "catapult",             "tier1",  "give the delta", "SC"),
  ("conceptualize",      "conceptualize",        "tier1",  "say what you designed", "S"),
  ("embark",             "embark",               "tier1",  "say what happened", "SCE"),
  ("endeavor",           "endeavor",             "tier1",  "name the work", "S"),
  ("multifaceted",       "multifaceted",         "tier1",  "name the facets", "KSE"),
  ("treasure-trove",     "treasure trove",       "tier1",  "say what is in it", "E"),
  ("beacon",             "beacon",               "tier1",  "name the thing", "E"),
  ("cornerstone",        "cornerstone",          "tier1",  "name the dependency", "SCE"),
  ("deep-dive",          "deep dive",            "tier1",  "name what was examined", "KCE"),
  ("dive-deep",          "dive deep",            "tier1",  "name what was examined", "C"),
  ("lets-dive-in",       "let's dive in",        "tier1",  "start", "SCE"),
  ("lets-dive-into",     "let's dive into",      "tier1",  "start", "SE"),
  ("lets-explore",       "let's explore",        "tier1",  "start", "SE"),
  ("lets-delve",         "let's delve",          "tier1",  "start", "E"),

  # --- puffery ---
  ("seamless",           "seamless",             "puffery", "say what fits what", "KSE"),
  ("seamlessly",         "seamlessly",           "puffery", "say what fits what", "E"),
  ("cutting-edge",       "cutting-edge",         "puffery", "say what is new about it", "SCE"),
  ("bleeding-edge",      "bleeding-edge",        "puffery", "say what is new about it", "E"),
  ("state-of-the-art",   "state-of-the-art",     "puffery", "give the comparison", "E"),
  ("groundbreaking",     "groundbreaking",       "puffery", "say what it broke", "WKSE"),
  ("game-changer",       "game-changer",         "puffery", "give the delta", "SCE"),
  ("game-changing",      "game-changing",        "puffery", "give the delta", "SE"),
  ("revolutionize",      "revolutionize",        "puffery", "give the delta", "KSCE"),
  ("transformative",     "transformative",       "puffery", "give the delta", "KSE"),
  ("unprecedented",      "unprecedented",        "puffery", "give the precedent it beats", "SE"),
  ("unparalleled",       "unparalleled",         "puffery", "give the comparison", "KE"),
  ("meticulous",         "meticulous",           "puffery", "say what care was taken", "WKSE"),
  ("meticulously",       "meticulously",         "puffery", "say what care was taken", "WKE"),
  ("intricate",          "intricate",            "puffery", "name the complication", "WKSE"),
  ("intricacies",        "intricacies",          "puffery", "name the complication", "W"),
  ("nuanced",            "nuanced",              "puffery", "name the nuance", "KE"),
  ("profound",           "profound",             "puffery", "give the measure", "WSE"),
  ("vibrant",            "vibrant",              "puffery", "describe it", "WSE"),
  ("boasts",             "boasts",               "puffery", "just say it has", "WKSE"),
  ("renowned",           "renowned",             "puffery", "say who says so", "WKE"),
  ("acclaimed",          "acclaimed",            "puffery", "say who says so", "E"),
  ("world-class",        "world-class",          "puffery", "give the comparison", "E"),
  ("best-in-class",      "best-in-class",        "puffery", "give the comparison", "E"),
  ("top-tier",           "top-tier",             "puffery", "give the comparison", "E"),
  ("industry-leading",   "industry-leading",     "puffery", "give the comparison", "E"),
  ("invaluable",         "invaluable",           "puffery", "give the value", "KE"),
  ("indispensable",      "indispensable",        "puffery", "say what breaks without it", "E"),
  ("paramount",          "paramount",            "puffery", "rank it against something", "CE"),
  ("pivotal",            "pivotal",              "puffery", "say what turned", "WKSE"),
  ("bespoke",            "bespoke",              "puffery", "say what was custom", "S"),
  ("unwavering",         "unwavering",           "puffery", "cut it", "S"),
  ("must-visit",         "must-visit",           "puffery", "cut it", "E"),
  ("must-have",          "must-have",            "puffery", "cut it", "own"),
  ("nestled",            "nestled",              "puffery", "say where it is", "WE"),
  ("in-the-heart-of",    "in the heart of",      "puffery", "say where it is", "WE"),
  ("picturesque",        "picturesque",          "puffery", "describe it", "E"),
  ("breathtaking",       "breathtaking",         "puffery", "describe it", "E"),

  # --- verb inflation ---
  ("leverage",           "leverage",             "verb",    "use a concrete verb", "WKSCE"),
  ("unlock",             "unlock",               "verb",    "say what it enables", "SCE"),
  ("unleash",            "unleash",              "verb",    "say what it enables", "SCE"),
  ("unveil",             "unveil",               "verb",    "say what was shown", "KSCE"),
  ("elevate",            "elevate",              "verb",    "give the delta", "KSCE"),
  ("empower",            "empower",              "verb",    "say what it permits", "SE"),
  ("foster",             "foster",               "verb",    "use a concrete verb", "WKSCE"),
  ("streamline",         "streamline",           "verb",    "say what was removed", "KSE"),
  ("amplify",            "amplify",              "verb",    "give the factor", "SE"),
  ("bolster",            "bolster",              "verb",    "use a concrete verb", "WKSE"),
  ("cultivate",          "cultivate",            "verb",    "use a concrete verb", "WSE"),
  ("underpin",           "underpin",             "verb",    "name the dependency", "E"),
  ("illuminate",         "illuminate",           "verb",    "say what you found", "KSE"),
  ("showcase",           "showcase",             "verb",    "say what it shows", "WKSE"),
  ("hone",               "hone",                 "verb",    "say what improved", "SC"),
  ("captivate",          "captivate",            "verb",    "cut it", "SC"),
  ("resonate",           "resonate",             "verb",    "say the effect", "SCE"),
  ("garner",             "garner",               "verb",    "use a concrete verb", "WK"),

  # --- transition crutches ---
  ("moreover",           "moreover",             "transition","connective throat-clearing", "SE"),
  ("furthermore",        "furthermore",          "transition","connective throat-clearing", "SE"),
  ("consequently",       "consequently",         "transition","connective throat-clearing", "KSE"),
  ("nevertheless",       "nevertheless",         "transition","connective throat-clearing", "SE"),
  ("nonetheless",        "nonetheless",          "transition","connective throat-clearing", "E"),
  ("in-conclusion",      "in conclusion",        "transition","cut it", "WCE"),
  ("in-summary",         "in summary",           "transition","cut it", "W"),
  ("in-essence",         "in essence",           "transition","cut it", "own"),
  ("generally-speaking", "generally speaking",   "transition","commit or give the number", "E"),
  ("broadly-speaking",   "broadly speaking",     "transition","commit or give the number", "own"),
  ("in-many-ways",       "in many ways",         "transition","name the ways", "E"),
  ("to-some-extent",     "to some extent",       "transition","give the extent", "E"),

  # --- flattery and social filler ---
  ("which-is-rare",      "which is rare",        "social",  "praise the thing, not the comparison", "own"),
  ("most-people-dont",   "most people don't",    "social",  "praise the thing, not the comparison", "own"),
  ("great-question",     "great question",       "social",  "answer it", "SE"),
  ("happy-to-help",      "happy to help",        "social",  "cut it", "E"),
  ("hope-this-helps",    "hope this helps",      "social",  "cut it", "E"),
  ("feel-free-to-reach", "feel free to reach out","social", "say what to do next", "E"),
  ("reach-out",          "reach out",            "social",  "say who contacts whom", "own"),
  ("thrilled-to-announce","thrilled to announce","social",  "just announce it", "E"),
  ("excited-to-share",   "excited to share",     "social",  "just share it", "E"),
  ("excited-to-announce","excited to announce",  "social",  "just announce it", "E"),
  ("humbled-and-honored","humbled and honored",  "social",  "cut it", "E"),
  ("as-you-know",        "as you know",          "social",  "then do not say it", "own"),

  # --- business jargon ---
  ("circle-back",        "circle back",          "jargon",  "say when and about what", "E"),
  ("lean-into",          "lean into",            "jargon",  "use a concrete verb", "E"),
  ("double-down",        "double down",          "jargon",  "say what increased", "E"),
  ("move-the-needle",    "move the needle",      "jargon",  "give the delta", "CE"),
  ("low-hanging-fruit",  "low-hanging fruit",    "jargon",  "name the task", "E"),
  ("moving-forward",     "moving forward",       "jargon",  "give the date", "E"),
  ("take-a-step-back",   "take a step back",     "jargon",  "cut it", "E"),
  ("unpack",             "unpack",               "jargon",  "just explain it", "KE"),
  ("secret-sauce",       "secret sauce",         "jargon",  "name the mechanism", "C"),
  ("secret-weapon",      "secret weapon",        "jargon",  "name the mechanism", "C"),

  # --- hyphenated cliches ---
  ("mission-critical",   "mission-critical",     "hyphen",  "say what fails without it", "E"),
  ("battle-tested",      "battle-tested",        "hyphen",  "say where it ran", "E"),
  ("out-of-the-box",     "out-of-the-box",       "hyphen",  "say what it does unconfigured", "E"),
  ("enterprise-grade",   "enterprise-grade",     "hyphen",  "name the property", "E"),
  ("plug-and-play",      "plug-and-play",        "hyphen",  "name the setup steps", "E"),
  ("purpose-built",      "purpose-built",        "hyphen",  "name the purpose", "E"),
  ("turnkey",            "turnkey",              "hyphen",  "name the setup steps", "E"),
  ("value-added",        "value-added",          "hyphen",  "name the value", "E"),
  ("laser-focused",      "laser-focused",        "hyphen",  "name the focus", "E"),
  ("tried-and-true",     "tried-and-true",       "hyphen",  "say where it ran", "E"),
  ("future-proof",       "future-proof",         "hyphen",  "name the change it survives", "E"),
  ("results-driven",     "results-driven",       "hyphen",  "give the results", "E"),
  ("customer-centric",   "customer-centric",     "hyphen",  "cut it", "E"),
  ("next-generation",    "next-generation",      "hyphen",  "give the version", "E"),

  # --- significance puffery, Wikipedia's family ---
  ("stands-as",          "stands as",            "signif",  "just say what it is", "W"),
  ("serves-as",          "serves as",            "signif",  "just say what it is", "WK"),
  ("plays-a-vital-role", "plays a vital role",   "signif",  "say what it does", "W"),
  ("plays-a-crucial-role","plays a crucial role","signif",  "say what it does", "WE"),
  ("plays-a-key-role",   "plays a key role",     "signif",  "say what it does", "W"),
  ("key-turning-point",  "key turning point",    "signif",  "say what turned", "W"),
  ("indelible-mark",     "indelible mark",       "signif",  "say what changed", "W"),
  ("deeply-rooted",      "deeply rooted",        "signif",  "give the history", "W"),
  ("focal-point",        "focal point",          "signif",  "name the thing", "W"),
  ("setting-the-stage",  "setting the stage for","signif",  "say what followed", "W"),
  ("reflects-broader",   "reflects broader",     "signif",  "name the pattern", "W"),
  ("valuable-insights",  "valuable insights",    "signif",  "give the insight", "WKE"),
  ("key-takeaways",      "key takeaways",        "signif",  "give them", "E"),
  ("a-wide-range-of",    "a wide range of",      "signif",  "give the range", "E"),
  ("diverse-array",      "diverse array",        "signif",  "give the count", "W"),

  # --- vague attribution ---
  ("studies-have-shown", "studies have shown",   "vague",   "cite one", "SE"),
  ("research-suggests",  "research suggests",    "vague",   "cite one", "SE"),
  ("experts-agree",      "experts agree",        "vague",   "name one", "SE"),
  ("experts-argue",      "experts argue",        "vague",   "name one", "W"),
  ("observers-have",     "observers have",       "vague",   "name one", "W"),
  ("industry-reports",   "industry reports",     "vague",   "cite one", "W"),
  ("some-critics-argue", "some critics argue",   "vague",   "name one", "W"),
  ("widely-believed",    "widely believed",      "vague",   "name who believes it", "own"),
  ("many-would-argue",   "many would argue",     "vague",   "name one", "own"),

  # --- filler grammar ---
  ("has-the-ability-to", "has the ability to",   "filler",  "can", "E"),
  ("a-large-number-of",  "a large number of",    "filler",  "give the number", "E"),
  ("during-the-course-of","during the course of","filler",  "during", "E"),
  ("in-close-proximity", "in close proximity to","filler",  "near", "E"),
  ("for-all-intents",    "for all intents and purposes","filler","cut it", "E"),
  ("in-spite-of-the-fact","in spite of the fact","filler",  "although", "E"),
  ("on-a-regular-basis", "on a regular basis",   "filler",  "give the interval", "E"),
  ("conduct-an-investigation","conduct an investigation","filler","investigate", "E"),
  ("provide-assistance-to","provide assistance to","filler","help", "E"),
  ("make-a-decision-on", "make a decision on",   "filler",  "decide", "E"),

  # --- closers ---
  ("at-the-end-of-the-day","at the end of the day","closer","cut it", "SCE"),
  ("all-is-said-and-done","when all is said and done","closer","cut it", "own"),
  ("the-bottom-line-is", "the bottom line is",   "closer",  "cut it", "own"),
  ("only-time-will-tell","only time will tell",  "closer",  "cut it", "own"),
  ("possibilities-are-endless","the possibilities are endless","closer","cut it", "own"),
  ("future-is-bright",   "the future is bright", "closer",  "cut it", "E"),
  ("one-thing-is-clear", "one thing is clear",   "closer",  "cut it", "own"),
  ("stay-tuned",         "stay tuned",           "closer",  "say when", "C"),
]

# Patterns a term cannot express.
RAW = [
  ("delve-infl",     r"\bdelv(?:e|es|ed|ing)\b",                       "tier1", "say what you looked at", "WKSCE"),
  ("underscore-infl",r"\bunderscor(?:e|es|ed|ing)\b",                  "tier1", "say the effect", "WKSE"),
  ("revolutionize-infl",r"\brevolutioniz(?:e|es|ed|ing)\b",            "puffery","give the delta", "KSCE"),
  ("leverage-infl",  r"\bleverag(?:e|es|ed|ing)\b",                    "verb",  "use a concrete verb", "WKSCE"),
  ("showcase-infl",  r"\bshowcas(?:e|es|ed|ing)\b",                    "verb",  "say what it shows", "WKSE"),
  ("foster-infl",    r"\bfoster(?:s|ed|ing)?\b",                       "verb",  "use a concrete verb", "WKSCE"),
  ("embark-infl",    r"\bembark(?:s|ed|ing)?\b",                       "tier1", "say what happened", "SCE"),
  ("not-only-but",   r"\bnot only\b[^.!?]{2,60}?\bbut\b",              "reframe","the not-only-but frame is an LLM cadence", "W"),
  ("not-x-its-y",    r"\b(?:it|this|that)(?:['\u2019]s| is) not\b[^.!?]{2,50}?[,\-\u2010-\u2015]\s*it(?:['\u2019]s| is)\b","reframe","the not-X-it-is-Y reframe is an LLM cadence", "WCE"),
  ("not-just-but",   r"\b(?:it|that|this)(?:'s| is)\s+not just\b[^.!?]{2,60}?\b(?:it(?:'s| is)|but)\b","reframe","the not-X-but-Y frame is an LLM cadence", "WCE"),
  ("additionally-initial", r"(?m)^\s*(?:Additionally|Moreover|Furthermore|Overall|Ultimately|Notably)\b", "transition","sentence-initial connective throat-clearing", "WKSE"),
  ("rule-of-three-adj", r"\b(\w+ly)\s+(\w+),\s+(\w+),\s+and\s+(\w+)\b","cadence","the rule-of-three list is an LLM cadence", "W"),
  ("foundational",   r"(?<!build-)\bfoundational\b(?!-software)",       "puffery","name the dependency", "KS"),
  ("as-an-ai",       r"\bas an AI\b",                                  "leak",  "assistant preamble leaked into the draft", "E"),
  ("knowledge-cutoff",r"\b(?:knowledge cutoff|last knowledge update)\b","leak", "assistant preamble leaked into the draft", "E"),
]

# --- wave two: words every source carries that I first held back as too
# --- ordinary for technical prose. Arm A and the estate-vocabulary threshold
# --- decide, rather than my caution.
TERMS += [
  ("robust",             "robust",               "puffery", "name the property", "WKSE"),
  ("comprehensive",      "comprehensive",        "puffery", "say what it covers", "KSE"),
  ("crucial",            "crucial",              "puffery", "rank it against something", "WKSE"),
  ("essential",          "essential",            "puffery", "say what breaks without it", "S"),
  ("vital",              "vital",                "puffery", "say what breaks without it", "WS"),
  ("remarkable",         "remarkable",           "puffery", "give the measure", "KS"),
  ("exceptional",        "exceptional",          "puffery", "give the measure", "KS"),
  ("innovative",         "innovative",           "puffery", "say what is new", "KSE"),
  ("scalable",           "scalable",             "puffery", "give the ceiling", "S"),
  ("versatile",          "versatile",            "puffery", "name the uses", "KS"),
  ("sophisticated",      "sophisticated",        "puffery", "name the mechanism", "own"),
  ("commendable",        "commendable",          "puffery", "cut it", "K"),
  ("compelling",         "compelling",           "puffery", "give the argument", "KSC"),
  ("formidable",         "formidable",           "puffery", "give the measure", "KC"),
  ("substantial",        "substantial",          "puffery", "give the number", "K"),
  ("noteworthy",         "noteworthy",           "puffery", "say why", "K"),
  ("distinctive",        "distinctive",          "puffery", "name the distinction", "K"),
  ("prevalent",          "prevalent",            "puffery", "give the frequency", "K"),
  ("inherent",           "inherent",             "puffery", "say where it comes from", "K"),
  ("adept",              "adept",                "puffery", "say at what", "K"),
  ("thorough",           "thorough",             "puffery", "say what was covered", "K"),
  ("interplay",          "interplay",            "puffery", "name the interaction", "W"),
  ("enduring",           "enduring",             "puffery", "give the duration", "WK"),
  ("rich",               "rich",                 "puffery", "say what is in it", "W"),
  ("vast",               "vast",                 "puffery", "give the size", "own"),
  ("a-host-of",          "a host of",            "puffery", "give the count", "own"),
  ("a-wealth-of",        "a wealth of",          "puffery", "give the count", "own"),
  ("utilize",            "utilize",              "verb",    "use", "KSE"),
  ("facilitate",         "facilitate",           "verb",    "use a concrete verb", "KS"),
  ("orchestrate",        "orchestrate",          "verb",    "say what runs what", "K"),
  ("pinpoint",           "pinpoint",             "verb",    "say what you found", "K"),
  ("scrutinize",         "scrutinize",           "verb",    "say what you checked", "K"),
  ("surpass",            "surpass",              "verb",    "give both numbers", "K"),
  ("shed-light-on",      "shed light on",        "verb",    "say what you found", "K"),
  ("usher-in",           "usher in",             "verb",    "say what started", "own"),
  ("unearth",            "unearth",              "verb",    "say what you found", "own"),
  ("mitigate",           "mitigate",             "verb",    "say what was reduced", "own"),
  ("necessitate",        "necessitate",          "verb",    "needs", "K"),
  ("imperative",         "imperative",           "verb",    "must", "K"),
  ("align-with",         "align with",           "verb",    "say what matches what", "WK"),
  ("ensure",             "ensure",               "verb",    "say what guarantees it", "WK"),
  ("encompass",          "encompass",            "verb",    "say what it covers", "WKS"),
  ("garner",             "garner",               "verb",    "use a concrete verb", "WK"),
  ("hinder",             "hinder",               "verb",    "say what slowed", "K"),
  ("impede",             "impede",               "verb",    "say what slowed", "K"),
  ("notably",            "notably",              "transition","say why", "KSE"),
  ("arguably",           "arguably",             "transition","commit or give the number", "S"),
  ("pragmatic",          "pragmatic",            "transition","say what you chose", "S"),
  ("actionable",         "actionable",           "jargon",  "name the action", "own"),
  ("granular",           "granular",             "jargon",  "give the grain", "own"),
  ("best-practices",     "best practices",       "jargon",  "name the practice", "own"),
  ("north-star",         "north star",           "jargon",  "name the goal", "own"),
  ("moving-parts",       "moving parts",         "jargon",  "name them", "own"),
  ("stakeholders",       "stakeholders",         "jargon",  "name them", "own"),
  ("roadmap",            "roadmap",              "jargon",  "give the dates", "own"),
  ("journey",            "journey",              "jargon",  "say what happened", "CE"),
  ("ecosystem",          "ecosystem",            "jargon",  "name the parts", "E"),
  ("backbone",           "backbone",             "jargon",  "name the dependency", "E"),
]
